CC = gcc

all: example p1a p1b p2

example: example.c
	$(CC) example.c -o example

p1a: p1a.c
	$(CC) p1a.c -o p1a

p1b: p1b.c
	$(CC) p1b.c -o p1b

p2: p2.c
	$(CC) p2.c -o p2

clean:
	rm example p1a p1b p2